@endpoint = http://localhost:3000/api/v1/cars



### Get all cars
GET  {{endpoint}} HTTP/3.0
content-type: application/json

### Post/create a new car and name this request "postACar"
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Mazda",
  "model": "Miata",
  "year": 1900
}

### 2. Capture the _id returned from the postACar request above
@newCar = {{postACar.response.body._id}}

### Get the newly created car by its captured ID
GET  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json



### Update the newly created car using the same captured ID
PUT  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Landcruiser",
  "year": 2026
}

###Delete the newly created car using the captured ID
DELETE  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah
