@endpoint = http://localhost:3000/api/v1/cars



### Get all cars
GET  {{endpoint}} HTTP/1.1
content-type: application/json

### Post/create a new car
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Honda",
  "model": "Fit"
}

### Get car by ID
# Replace 'PASTE_MONGO_ID_HERE' with the actual MongoDB ID
GET  {{endpoint}}/PASTE_MONGO_ID_HERE HTTP/1.1
content-type: application/json


### Put/update a car by ID
# Replace 'PASTE_MONGO_ID_HERE' with the actual MongoDB ID
PUT  {{endpoint}}/6ab3badc7fde30869d188191 HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Camry Hybrid"
}

###Delete a car by ID
# Replace 'PASTE_MONGO_ID_HERE' with the actual MongoDB ID
DELETE  {{endpoint}}/6ab3baf37fde30869d188192 HTTP/1.1
content-type: application/json
